name: compendium.aclhelpers pipeline
on:
  push
defaults:
  run:
    shell: pwsh
#    working-directory: ci/scripts 
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: dir #./Debug-Scripts.ps1 -Path "$env:GITHUB_WORKSPACE/src/Compendium.AclHelpers"