name: compendium.aclhelpers pipeline
on:
  push
default:
  run:
    shell: pwsh
    working-directory: ./ci/scripts 
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: ./Debug-Scripts.ps1 -Path "$env:GITHUB_WORKSPACE/src/Compendium.AclHelpers"