name: compendium.aclhelpers pipeline
on:
  push
defaults:
  run:
    shell: pwsh
    working-directory: ci/scripts 
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run PSScriptAnalyzer
      run: |
        ./Debug-Scripts.ps1 -Path "$env:GITHUB_WORKSPACE/src/Compendium.AclHelpers"