name: compendium.aclhelpers pipeline
on:
  push
defaults:
  run:
    shell: pwsh
    working-directory: build/scripts 
jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run PSScriptAnalyzer
      run: |
        ./Debug-Scripts.ps1 -Path "$env:GITHUB_WORKSPACE/src/Compendium.AclHelpers"
    - name: Run Pester Tests
      run: |
        ./Test-Module.ps1